[program:autossh-tunnels]
command=/usr/bin/bash /home/utylee/temp/bin/autossh-tunnels.sh
directory=/home/utylee/temp/bin
user=utylee
autostart=true
autorestart=true
startsecs=5
environment=HOME="/home/utylee",USER="utylee",PATH="/usr/local/bin:/usr/bin:/bin"
stdout_logfile=/home/utylee/logs/supervisor-autossh.log
stderr_logfile=/home/utylee/logs/supervisor-autossh.err
stopasgroup=true
killasgroup=true

# [program:autossh-tunnels]
# command=/usr/bin/bash /home/utylee/temp/bin/autossh-tunnels.sh
# directory=/home/utylee/temp/bin
# autostart = true
# autorestart = true
# user=utylee
